# Generated by Django 5.0.2 on 2024-04-30 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.CharField(db_index=True, default='', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('title', models.CharField(max_length=40)),
                ('isActive', models.BooleanField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('adress', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default='', primary_key=True, serialize=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
