# Generated by Django 5.0.2 on 2024-05-01 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtkinlikKatilim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('etkinlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.etkinlik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'etkinlik')},
            },
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='katilimcilar',
            field=models.ManyToManyField(related_name='katildigi_etkinlikler', through='main.EtkinlikKatilim', to=settings.AUTH_USER_MODEL),
        ),
    ]
